### ISSUE TITLE
Receiving `UnicodeDecodeError` while compiling

### ISSUE THREAD

**Issue by sevasoft** [ApeWorX/ape-solidity#49]
## Overview

Receiving the error `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte` while compiling solidity smart contracts.

The error occurs evidently from the `ape-solidity` plugin.

```bash
(venv) mbp:truhuis-smart-contracts mac$ ape compile
WARNING: Unprocessed plugin config(s): scripts_folder, tests_folder. Plugins may not be installed yet or keys may be mis-spelled.
WARNING: Unprocessed plugin config(s): scripts_folder, tests_folder. Plugins may not be installed yet or keys may be mis-spelled.
WARNING: Unprocessed plugin config(s): scripts_folder, tests_folder. Plugins may not be installed yet or keys may be mis-spelled.
WARNING: Unprocessed plugin config(s): scripts_folder, tests_folder. Plugins may not be installed yet or keys may be mis-spelled.
INFO: Compiling 'BrownieContract.sol'.
Traceback (most recent call last):
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/bin/ape", line 8, in <module>
    sys.exit(cli())
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/ape/_cli.py", line 40, in invoke
    return super().invoke(ctx)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/ape_compile/_cli.py", line 53, in cli
    contract_types = cli_ctx.project_manager.load_contracts(
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/ape/managers/project/manager.py", line 422, in load_contracts
    manifest = self._project.create_manifest(file_paths, use_cache=use_cache)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/ape/managers/project/types.py", line 158, in create_manifest
    compiled_contract_types = self.compiler_manager.compile(list(needs_compiling))
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/ape/managers/compilers.py", line 98, in compile
    compiled_contracts = self.registered_compilers[extension].compile(
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/ape_solidity/compiler.py", line 214, in compile
    files_by_solc_version = self.get_version_map(contract_filepaths, base_path=contracts_path)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/ape_solidity/compiler.py", line 369, in get_version_map
    imports = self.get_imports(get_all_files_in_directory(contracts_path), contracts_path)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/ape_solidity/compiler.py", line 334, in get_imports
    source_lines = filepath.read_text().splitlines()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1133, in read_text
    return f.read()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte
(venv) mbp:truhuis-smart-contracts mac$ ls -al
```

## How to solve

In order to escape the error and compile I have to remove `.DS_Store` file inside of `contracts` folder each time and after that run `ape compile`. It would be nice to avoid manually remove that file or to modify the plugin so that the error not occurs.

**Comment by antazoey** [comment]
This got fixed from this PR https://github.com/ApeWorX/ape-solidity/pull/73 wayyyy back.
The fix made it so only Solidity files are passed around, so the .DS_Store is never attempted to be read.
