### ISSUE TITLE
bug: unable to import local sol files

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape-solidity#5]
```
(brownie) sabotage@sabotage:~/ape$ brownie bake token
Brownie v1.15.1 - Python development framework for Ethereum

Downloading from https://github.com/brownie-mix/token-mix/archive/master.zip...
9.13kiB [00:00, 3.69MiB/s]
SUCCESS: Brownie mix 'token' has been initiated at /home/sabotage/ape/token
(brownie) sabotage@sabotage:~/ape$ pyenv deactivate
sabotage@sabotage:~/ape$ pyenv activate apeworx
pyenv-virtualenv: prompt changing will be removed from future release. configure `export PYENV_VIRTUALENV_DISABLE_PROMPT=1' to simulate the behavior.
(apeworx) sabotage@sabotage:~/ape$ cd token/
(apeworx) sabotage@sabotage:~/ape/token$ ape compile
INFO: Compiling 'contracts/Token.sol'
INFO: Compiling 'contracts/SafeMath.sol'
Traceback (most recent call last):
  File "/home/sabotage/.pyenv/versions/apeworx/bin/ape", line 8, in <module>
    sys.exit(cli())
  File "/home/sabotage/.pyenv/versions/3.8.10/envs/apeworx/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/sabotage/.pyenv/versions/3.8.10/envs/apeworx/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/sabotage/.pyenv/versions/3.8.10/envs/apeworx/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sabotage/.pyenv/versions/3.8.10/envs/apeworx/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sabotage/.pyenv/versions/3.8.10/envs/apeworx/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/sabotage/.pyenv/versions/3.8.10/envs/apeworx/lib/python3.8/site-packages/ape_compile/_cli.py", line 75, in cli
    contract_types = project.load_contracts(use_cache)
  File "/home/sabotage/.pyenv/versions/3.8.10/envs/apeworx/lib/python3.8/site-packages/ape/managers/project.py", line 117, in load_contracts
    contract_types.update(self.compilers.compile(list(needs_compiling)))
  File "/home/sabotage/.pyenv/versions/3.8.10/envs/apeworx/lib/python3.8/site-packages/ape/managers/compilers.py", line 49, in compile
    for contract_type in self.registered_compilers[extension].compile(paths_to_compile):
  File "/home/sabotage/ape/ape-solidity/ape_solidity/compiler.py", line 77, in compile
    for result in solcx.compile_source(
  File "/home/sabotage/.pyenv/versions/3.8.10/envs/apeworx/lib/python3.8/site-packages/solcx/main.py", line 112, in compile_source
    return _compile_combined_json(
  File "/home/sabotage/.pyenv/versions/3.8.10/envs/apeworx/lib/python3.8/site-packages/solcx/main.py", line 288, in _compile_combined_json
    stdoutdata, stderrdata, command, proc = wrapper.solc_wrapper(
  File "/home/sabotage/.pyenv/versions/3.8.10/envs/apeworx/lib/python3.8/site-packages/solcx/wrapper.py", line 158, in solc_wrapper
    raise SolcError(
solcx.exceptions.SolcError: An error occurred during execution
> command: `/home/sabotage/.solcx/solc-v0.6.12 --combined-json abi,bin,bin-runtime,devdoc,userdoc -`
> return code: `1`
> stdout:

> stderr:
Error: Source "SafeMath.sol" not found: File not found.
 --> <stdin>:5:1:
  |
5 | import "./SafeMath.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by sabotagebeats** [comment]
```
(apeworx) sabotage@sabotage:~/ape/token$ ape plugins list
WARNING: $GITHUB_ACCESS_TOKEN not set, skipping 2nd class plugins
Installed plugins:
  ape_solidity (0.1.0a1)
  ape_vyper (0.1.0a6)
(apeworx) sabotage@sabotage:~/ape/token$ ape --version
0.1.0a17
```

**Comment by sabotagebeats** [comment]
duplicate issue https://github.com/ApeWorX/ape-solidity/issues/6
