### ISSUE TITLE
Receiving `ValueError: substring not found` while compiling

### ISSUE THREAD

**Issue by sevasoft** [ApeWorX/ape-solidity#50]
Any idea on why this error reverted? I've tried to compile that solidity interface in another development framework and didn't receive that kind of issue.

```bash
(venv) mbp:truhuis-smart-contracts mac$ ape compile contracts/interfaces/ITruhuisAuction.sol 
INFO: Compiling 'interfaces/ITruhuisAuction.sol'.
Traceback (most recent call last):
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/bin/ape", line 8, in <module>
    sys.exit(cli())
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/ape/_cli.py", line 40, in invoke
    return super().invoke(ctx)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/ape_compile/_cli.py", line 53, in cli
    contract_types = cli_ctx.project_manager.load_contracts(
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/ape/managers/project/manager.py", line 422, in load_contracts
    manifest = self._project.create_manifest(file_paths, use_cache=use_cache)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/ape/managers/project/types.py", line 158, in create_manifest
    compiled_contract_types = self.compiler_manager.compile(list(needs_compiling))
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/ape/managers/compilers.py", line 98, in compile
    compiled_contracts = self.registered_compilers[extension].compile(
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/ape_solidity/compiler.py", line 214, in compile
    files_by_solc_version = self.get_version_map(contract_filepaths, base_path=contracts_path)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/ape_solidity/compiler.py", line 369, in get_version_map
    imports = self.get_imports(get_all_files_in_directory(contracts_path), contracts_path)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/ape_solidity/compiler.py", line 353, in get_imports
    import_item = import_str_to_source_id(import_str=import_str, source_path=filepath)
  File "/Users/mac/P_D_V/projects-current/truhuis/tmp/truhuis-smart-contracts/venv/lib/python3.10/site-packages/ape_solidity/compiler.py", line 301, in import_str_to_source_id
    end_index = import_str.index(quote) + 1
ValueError: substring not found
```

**Comment by unparalleled-js** [comment]
Are you still experiencing this issue? I just tried off main and was not able to reproduce.

**Comment by antazoey** [comment]
Likely was fixed here: https://github.com/ApeWorX/ape-solidity/pull/80

But here is some more info.
Using this config:

```yaml
name: truhuis-smart-contracts

contracts_folder: src

plugins:
  - name: solidity
  - name: hardhat

default_ecosystem: ethereum

compile:
  exclude:
    - mocks/*

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.6.0
  - name: ChainLink
    github: smartcontractkit/chainlink-brownie-contracts
    version: 0.8.0
    config_override:
      contracts_folder: contracts/src/v0.8

solidity:
  import_remapping:
    - "@openzeppelin/contracts=OpenZeppelin/4.6.0"
    - "@chainlink/contracts=ChainLink/0.8.0"

hardhat:
  port: 8555

ethereum:
  default_network: local
  local:
    default_provider: hardhat
```

and changing visibilitiy modifier in `ATruhuisAddressRegistry.getMunicipality` from internal to external (matching the interface with Solc is saying is required), everything compiles.

**NOTE**: I have had issues like the visibility-modifier thing before and it makes me wonder why Foundry's solc doesnt care.

thanks for raising the issue. sorry it took to so long to address.
